# Generated by Django 5.2.4 on 2025-07-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_national_code_userprofile_national_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
    ]
